version: "3"
services:
  jenkins:
    container_name: jenkins
    image: my_jenkins_docker:v2
    volumes:
     - '/home/aleks/Documents/PASV_DevOps/MyGitHub/Backup/jenkins_bck_111323/var/lib/jenkins/:/var/jenkins_home:rw'
    ports:
    - 8080:8080
    - 8090:8090
volumes:
  jenkins-data:
networks:
  jenkins:
    external: true