version: "3"
services:
  jenkins:
    container_name: jenkins
    image: my_jenkins_docker:v1
    volumes:
     - '/home/aleks/Documents/PASV_DevOps/MyGitHub/DevOps_Group_3/Docker/docker_jenkins/jenkins:/var/jenkins_home:rw'
    ports:
    - 8080:8080
    - 8090:8090
volumes:
  jenkins-data:
networks:
  jenkins:
    external: true