# A simple example of ClusterConfig object with two nodegroups:
--- 
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-k8s-cluster
  region: us-east-1

nodeGroups:
  - name: ng1-public
    instanceType: t3.small
    instanceName: EKS-inst
    desiredCapacity: 2
  - name: ng2-private
    instanceType: t3.small
    desiredCapacity: 2
    privateNetworking: true