version: '3'

services:
  nodejs-app:
    image: jessehoch/pacman-nodejs-app:latest
    ports:
      - "8080:8080"  # Map port 8080 of the container to port 8080 on the host
    environment:
      MONGO_SERVICE_HOST: mongo
      MONGO_AUTH_USER: space-inv
      MONGO_AUTH_PWD: space-inv
      MONGO_DATABASE: space-inv
    restart: unless-stopped

  mongo:
   image: mongo:4.0.4
   ports:
     - "27017:27017" # Expose MongoDB on port 27017
   volumes:
     - mongo-db:/data/db
     - ./mongo-init-db/init_user_db.js:/docker-entrypoint-initdb.d/init_user_db.js:ro  # Mount the initialization script directory
   restart: unless-stopped
volumes:
  mongo-db:
    driver: local
  mongo-initdb:
    driver: local
    driver_opts:
      type: none
      device: /home/aleks/Documents/PASV_DevOps/MyGitHub/DevOps_Group_3/Docker/space_invaders_mine/mongo-init-db # need folder mongo-init-db in the same folder as docker-compose.yml
      o: bind
networks:
  default:
    external:
      name: space-inv-network